language: java

# enable container-based architecture and caching
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle/caches/

jdk:
  - oraclejdk8 # JavaFX 8 only works under Oracle JDK 8

# allow GUI testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script: npm install -g buster

script: ./gradlew check busterTest
